name: build-docs
on:
  push:
    branches:
      - master
      - main
      - devel
    paths:
      - 'docs/**'
  pull_request:
permissions:
  contents: read

jobs:
  par2cron:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
        cache: false

    - name: Install Asciidoc
      run: sudo apt-get update && sudo apt-get install -y asciidoc w3m

    - name: Clean the environment
      run: make clean

    - name: Vendor the application
      run: make vendor

    - name: Build the documentation
      run: make docs

    - name: Check if committed documentation needs updating
      run: make is-clean
