name: golang-tests
on:
  push:
    branches:
      - master
      - main
      - devel
  pull_request:
permissions:
  contents: read
jobs:
  golang:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Install par2cmdline
        run: sudo apt-get update && sudo apt-get install -y par2

      - name: Clean the environment
        run: make clean

      - name: Run all Go tests
        run: make test

      - name: Clean the environment (for end-to-end tests)
        run: make clean

      - name: Vendor the application (for end-to-end tests)
        run: make vendor

      - name: Build the application (for end-to-end tests)
        run: make par2cron

      - name: Run all end-to-end tests
        run: bash ./scripts/golang-tests-e2e.sh
