name: golang-build
on:
  push:
    branches:
      - master
      - main
      - devel
  pull_request:
permissions:
  contents: read
jobs:
  golang:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Clean the environment
        run: make clean

      - name: Vendor the application for production
        run: make vendor

      - name: Build the application for production
        run: make par2cron
